'use strict';
/* English names of places (states, cities, seas) that the map data has in Bosnian/Serbian: RA.tn(name), src/00a-i18n.js.
   A name missing here stays as it is (most are the same in English). */
RA.EN_NAMES = {
  "Evropa": "Europe", "Cijeli svijet": "The whole world", "Orešek": "Oreshek", "Kruševac": "Krusevac",
  "Abidžan": "Abidjan", "Abo": "Åbo", "Abu Dabi": "Abu Dhabi", "Abudža": "Abuja",
  "Adelejd": "Adelaide", "Adenski zaljev": "Gulf of Aden", "Adis Abeba": "Addis Ababa", "Afganistan": "Afghanistan",
  "Ajmarska kraljevstva": "Aymara kingdoms", "Ajutaja": "Ayutthaya", "Akonkagva": "Aconcagua", "Akra": "Accra",
  "Aksumsko kraljevstvo": "Kingdom of Aksum", "Akve S.": "Aquae S.", "Akvinkum": "Aquincum", "Albanija": "Albania",
  "Albanske kneževine": "Albanian principalities", "Aleksandrija": "Alexandria", "Alep": "Aleppo", "Algonkinska plemena": "Algonquian tribes",
  "Aljaski zaljev": "Gulf of Alaska", "Alžir": "Algeria", "Alžirski dejlik": "Deylik of Algiers", "Andamansko more": "Andaman Sea",
  "Andautonija": "Andautonia", "Andavajlas": "Andahuaylas", "Andska plemena": "Andean tribes", "Andske kneževine": "Andean principalities",
  "Ankira": "Ancyra", "Antverpen": "Antwerp", "Anšan": "Anshan", "Arafursko more": "Arafura Sea",
  "Arapsko more": "Arabian Sea", "Arauko": "Arauco", "Argentorat": "Argentoratum", "Arhangelsk": "Arkhangelsk",
  "Armenija": "Armenia", "Artašat": "Artashat", "Asam": "Assam", "Astečki savez": "Aztec Triple Alliance",
  "Asuan": "Aswan", "Asunsion": "Asunción", "Atabaskanci": "Athabaskans", "Atalija": "Attalia",
  "Atena": "Athens", "Atina": "Athens", "Atlantski okean": "Atlantic Ocean", "Augusta Raurika": "Augusta Raurica",
  "Australija": "Australia", "Austrija": "Austria", "Austrijsko carstvo": "Austrian Empire", "Austro-Ugarska": "Austria-Hungary",
  "Azak": "Azaq", "Azerbejdžan": "Azerbaijan", "Azovsko more": "Sea of Azov", "Ašantsko carstvo": "Ashanti Empire",
  "Ašhabad": "Ashgabat", "Bahami": "Bahamas", "Balearsko more": "Balearic Sea", "Baltimor": "Baltimore",
  "Baltičko more": "Baltic Sea", "Bangalor": "Bangalore", "Bangi": "Bangui", "Bangladeš": "Bangladesh",
  "Bantu plemena": "Bantu tribes", "Banžul": "Banjul", "Barankas": "Barrancas", "Barankilja": "Barranquilla",
  "Barentsovo more": "Barents Sea", "Batavija": "Batavia", "Bavarska": "Bavaria", "Bazel": "Basel",
  "Bejrut": "Beirut", "Belem": "Belém", "Belgija": "Belgium", "Belo Orizonte": "Belo Horizonte",
  "Bengalski zaljev": "Bay of Bengal", "Bengazi": "Benghazi", "Beograd": "Belgrade", "Beotuci": "Beothuk",
  "Beotuk": "Beothuk", "Beringovo more": "Bering Sea", "Berit": "Berytus", "Beroja": "Beroea",
  "Beč": "Vienna", "Bijelo more": "White Sea", "Birmingem": "Birmingham", "Bisao": "Bissau",
  "Biskajski zaljev": "Bay of Biscay", "Bitolj": "Bitola", "Bizant": "Byzantium", "Bizantsko carstvo": "Byzantine Empire",
  "Biškek": "Bishkek", "Bjelorusija": "Belarus", "Bocvana": "Botswana", "Bojsi": "Boise",
  "Bolivija": "Bolivia", "Bombaj": "Bombay", "Bon": "Bonn", "Bononija": "Bononia",
  "Bopal": "Bhopal", "Bordo": "Bordeaux", "Bosna i Hercegovina": "Bosnia and Herzegovina", "Bosporsko kraljevstvo": "Bosporan Kingdom",
  "Botnički zaljev": "Gulf of Bothnia", "Brakara": "Bracara", "Brazavil": "Brazzaville", "Brazilija": "Brasília",
  "Bretanja": "Brittany", "Brigantijum": "Brigantium", "Brisel": "Brussels", "Britanija": "Britain",
  "Britanska Indija": "British India", "Britansko carstvo": "British Empire", "Brizbejn": "Brisbane", "Brunej": "Brunei",
  "Budim": "Buda", "Budimpešta": "Budapest", "Budžumbura": "Bujumbura", "Buenos Ajres": "Buenos Aires",
  "Bugarska": "Bulgaria", "Buhara": "Bukhara", "Bukurešt": "Bucharest", "Caodžuang": "Zaozhuang",
  "Caricin": "Tsaritsyn", "Carigrad": "Constantinople", "Carstvo Han": "Han Empire", "Carstvo Mali": "Mali Empire",
  "Carstvo Ojo": "Oyo Empire", "Carstvo Ćing": "Qing Empire", "Carstvo Čimu": "Chimú Empire", "Cejlon": "Ceylon",
  "Centralnoafrička Republika": "Central African Republic", "Cibo": "Zibo", "Cirih": "Zurich", "Crna Gora": "Montenegro",
  "Crno more": "Black Sea", "Crveno more": "Red Sea", "DR Kongo": "DR Congo", "Dablin": "Dublin",
  "Dahomej": "Dahomey", "Daka": "Dhaka", "Dakija": "Dacia", "Dalas": "Dallas",
  "Dalijan": "Dalian", "Damask": "Damascus", "Dancig": "Danzig", "Danska": "Denmark",
  "Dar es Salam": "Dar es Salaam", "Daćing": "Daqing", "Delhijski sultanat": "Delhi Sultanate", "Dirahij": "Dyrrachium",
  "Diseldorf": "Düsseldorf", "Dnjepar": "Dnieper", "Dnjepropetrovsk": "Dnipropetrovsk", "Dominikanska Republika": "Dominican Republic",
  "Drač": "Durrës", "Drezden": "Dresden", "Duala": "Douala", "Durranijsko carstvo": "Durrani Empire",
  "Dušanbe": "Dushanbe", "Džajpur": "Jaipur", "Džakarta": "Jakarta", "Džanđijang": "Zhanjiang",
  "Džebel Mara": "Jebel Marra", "Džene": "Djenné", "Džene-Dženo": "Djenné-Djenno", "Džengdžou": "Zhengzhou",
  "Džibuti": "Djibouti", "Džida": "Jeddah", "Džordžtaun": "Georgetown", "Džuba": "Juba",
  "Edinburg": "Edinburgh", "Egejsko more": "Aegean Sea", "Egipat": "Egypt", "Ekvatorija": "Equatoria",
  "Ekvatorijalna Gvineja": "Equatorial Guinea", "Eminij": "Aeminium", "Emirat Nedžd": "Emirate of Nejd", "Engleska": "England",
  "Epidaur": "Epidaurum", "Epirska despotovina": "Despotate of Epirus", "Eritreja": "Eritrea", "Estonija": "Estonia",
  "Esvatini": "Eswatini", "Etiopija": "Ethiopia", "Etiopsko carstvo": "Ethiopian Empire", "Fantski savez": "Fante Confederacy",
  "Fes": "Fez", "Fidži": "Fiji", "Filadelfija": "Philadelphia", "Filipini": "Philippines",
  "Filipinsko more": "Philippine Sea", "Filipopolj": "Philippopolis", "Finiks": "Phoenix", "Finska": "Finland",
  "Finski zaljev": "Gulf of Finland", "Firenca": "Florence", "Firentinska republika": "Republic of Florence", "Florencija": "Florentia",
  "Francuska": "France", "Fritaun": "Freetown", "Fudžou": "Fuzhou", "Gaja": "Gaya",
  "Gambija": "Gambia", "Gana": "Ghana", "Garamanti": "Garamantes", "Gdanjsk": "Gdańsk",
  "Getulija": "Gaetulia", "Gojanija": "Goiânia", "Gornja Volta": "Upper Volta", "Granadski emirat": "Emirate of Granada",
  "Grenland": "Greenland", "Gruzija": "Georgia", "Grčka": "Greece", "Guangdžou": "Guangzhou",
  "Gudžranvala": "Gujranwala", "Guijang": "Guiyang", "Gvadalahara": "Guadalajara", "Gvajakil": "Guayaquil",
  "Gvajana": "Guyana", "Gvarani": "Guaraní", "Gvatemala": "Guatemala", "Gvineja": "Guinea",
  "Gvineja Bisao": "Guinea-Bissau", "Gvinejski zaljev": "Gulf of Guinea", "Habarovsk": "Khabarovsk", "Hafsidski sultanat": "Hafsid Sultanate",
  "Hag": "The Hague", "Hajderabad": "Hyderabad", "Hajfong": "Haiphong", "Halifaks": "Halifax",
  "Hangdžou": "Hangzhou", "Hanoj": "Hanoi", "Harkiv": "Kharkiv", "Harkov": "Kharkov",
  "Hausa gradovi": "Hausa city-states", "Havajsko kraljevstvo": "Kingdom of Hawaii", "Hefej": "Hefei", "Herakleja": "Heraclea",
  "Hersones": "Chersonesus", "Hesen": "Hesse", "Hibernija": "Hibernia", "Himjarsko kraljevstvo": "Himyarite Kingdom",
  "Hinduistička kraljevstva": "Hindu kingdoms", "Hipon": "Hippo", "Hirošima": "Hiroshima", "Hjuston": "Houston",
  "Ho Ši Min": "Ho Chi Minh City", "Holandija": "Netherlands", "Honijara": "Honiara", "Hrvatska": "Croatia",
  "Hudsonov zaljev": "Hudson Bay", "Ikitos": "Iquitos", "Ikonij": "Iconium", "Ikozijum": "Icosium",
  "Indija": "India", "Indijski okean": "Indian Ocean", "Indonezija": "Indonesia", "Irokezi": "Iroquois",
  "Irska": "Ireland", "Irska kraljevstva": "Irish kingdoms", "Irsko more": "Irish Sea", "Island": "Iceland",
  "Istočna Njemačka": "East Germany", "Istočni Timor": "East Timor", "Istočno kinesko more": "East China Sea", "Italija": "Italy",
  "Izrael": "Israel", "Jadransko more": "Adriatic Sea", "Jamajka": "Jamaica", "Jamusukro": "Yamoussoukro",
  "Jangon": "Yangon", "Janjina": "Ioannina", "Japansko carstvo": "Empire of Japan", "Japansko more": "Sea of Japan",
  "Jaragva": "Jaraguá", "Jarkand": "Yarkand", "Jaunde": "Yaoundé", "Javansko more": "Java Sea",
  "Jekaterinburg": "Yekaterinburg", "Jekaterinodar": "Yekaterinodar", "Jemen": "Yemen", "Jentaj": "Yantai",
  "Jerevan": "Yerevan", "Jermenija": "Armenia", "Jerusalim": "Jerusalem", "Jonsko more": "Ionian Sea",
  "Jugoslavija": "Yugoslavia", "Jumen": "Yumen", "Južna Koreja": "South Korea", "Južni Sjongnu": "Southern Xiongnu",
  "Južni Sudan": "South Sudan", "Južni Vijetnam": "South Vietnam", "Južno kinesko more": "South China Sea", "Južnoafrička Republika": "South Africa",
  "Južnoafrička Unija": "Union of South Africa", "Kahokija": "Cahokia", "Kairo": "Cairo", "Kaledonija": "Caledonia",
  "Kalgari": "Calgary", "Kalifornijski zaljev": "Gulf of California", "Kalinjin": "Kalinin", "Kalkuta": "Calcutta",
  "Kalmarska unija": "Kalmar Union", "Kaluse": "Calusa", "Kambodža": "Cambodia", "Kamerun": "Cameroon",
  "Kampinas": "Campinas", "Kanada": "Canada", "Kanbera": "Canberra", "Kanjon de Šej": "Canyon de Chelly",
  "Kanton": "Canton", "Kaosjung": "Kaohsiung", "Karakas": "Caracas", "Karalis": "Carales",
  "Karamanski bejlik": "Beylik of Karaman", "Karači": "Karachi", "Karibi": "Caribs", "Karipska plemena": "Carib tribes",
  "Karipsko more": "Caribbean Sea", "Karlsrue": "Karlsruhe", "Kartagina": "Carthage", "Kartum": "Khartoum",
  "Kasel": "Kassel", "Kaspijsko jezero": "Caspian Sea", "Kastilja": "Castile", "Katak": "Cuttack",
  "Katana": "Catana", "Katanija": "Catania", "Katar": "Qatar", "Kavači": "Cahuachi",
  "Kazablanka": "Casablanca", "Kazahstan": "Kazakhstan", "Kašmir": "Kashmir", "Kejptaun": "Cape Town",
  "Keln": "Cologne", "Kenigsberg": "Königsberg", "Kenija": "Kenya", "Khmersko carstvo": "Khmer Empire",
  "Kijev": "Kyiv", "Kilva": "Kilwa", "Kimberli": "Kimberley", "Kimhe": "Gimhae",
  "Kina": "China", "Kinšasa": "Kinshasa", "Kipar": "Cyprus", "Kiparsko kraljevstvo": "Kingdom of Cyprus",
  "Kirgistan": "Kyrgyzstan", "Kito": "Quito", "Kizilorda": "Kyzylorda", "Kišinjev": "Chișinău",
  "Kjongdžu": "Gyeongju", "Kjoto": "Kyoto", "Klivlend": "Cleveland", "Kluž": "Cluj",
  "Kogurjo": "Goguryeo", "Koimbatur": "Coimbatore", "Kojsani": "Qoyllur", "Kolombo": "Colombo",
  "Kolonija": "Colonia", "Kolumbija": "Colombia", "Konakri": "Conakry", "Kongo": "Congo",
  "Kongo (Brazavil)": "Congo (Brazzaville)", "Kongo (Leopoldvil)": "Congo (Léopoldville)", "Konja": "Konya", "Konstantin": "Constantine",
  "Konstantinopolj": "Constantinople", "Kopenhagen": "Copenhagen", "Koralno more": "Coral Sea", "Kordoba": "Córdoba",
  "Koreja": "Korea", "Kostarika": "Costa Rica", "Koči": "Kochi", "Krakov": "Kraków",
  "Kraljevina Bosna": "Kingdom of Bosnia", "Kraljevina Dvije Sicilije": "Kingdom of the Two Sicilies", "Kraljevina Italija": "Kingdom of Italy", "Kraljevina Jugoslavija": "Kingdom of Yugoslavia",
  "Kraljevina Sardinija": "Kingdom of Sardinia", "Kraljevina Sicilija": "Kingdom of Sicily", "Kraljevina Ugarska": "Kingdom of Hungary", "Kraljevstvo Ava": "Kingdom of Ava",
  "Kraljevstvo Benin": "Kingdom of Benin", "Kraljevstvo Cusco": "Kingdom of Cusco", "Kraljevstvo Kongo": "Kingdom of Kongo", "Kraljevstvo Merina": "Merina Kingdom",
  "Kraljevstvo Saka": "Saka Kingdom", "Krasnojarsk": "Krasnoyarsk", "Kristijanija": "Christiania", "Ktesifon": "Ctesiphon",
  "Kuba": "Cuba", "Kujaba": "Cuiabá", "Kuljakan": "Culiacán", "Kultura Hopvel": "Hopewell culture",
  "Kultura Lorel": "Laurel culture", "Kultura Marksvil": "Marksville culture", "Kultura Nok": "Nok culture", "Kultura Sao": "Sao culture",
  "Kultura Svift Krik": "Swift Creek culture", "Kuritiba": "Curitiba", "Kuvajt": "Kuwait", "Kučing": "Kuching",
  "Kušansko carstvo": "Kushan Empire", "Kušitski stočari": "Cushitic herders", "Kvebek": "Quebec", "Kvinkan": "Quinkan",
  "La Korunja": "A Coruña", "Labradorsko more": "Labrador Sea", "Lahor": "Lahore", "Laknau": "Lucknow",
  "Lamanš": "English Channel", "Landžou": "Lanzhou", "Laponija": "Lapland", "Lasa": "Lhasa",
  "Latvija": "Latvia", "Lavlok": "Lovelock", "Lavov": "Lviv", "Lenjingrad": "Leningrad",
  "Lentija": "Lentia", "Leopoldvil": "Léopoldville", "Levantsko more": "Levantine Sea", "Liban": "Lebanon",
  "Liberija": "Liberia", "Libija": "Libya", "Librevil": "Libreville", "Ligursko more": "Ligurian Sea",
  "Lijež": "Liège", "Lil": "Lille", "Lilongve": "Lilongwe", "Linji": "Linyi",
  "Lion": "Lyon", "Lisabon": "Lisbon", "Litvanija": "Lithuania", "Lome": "Lomé",
  "Londinijum": "Londinium", "Los Anđeles": "Los Angeles", "Lourenso Markes": "Lourenço Marques", "Lođ": "Łódź",
  "Ludijana": "Ludhiana", "Luksemburg": "Luxembourg", "Luojang": "Luoyang", "Lutecija": "Lutetia",
  "Madagaskar": "Madagascar", "Majami": "Miami", "Majanski gradovi": "Maya cities", "Maje": "Maya",
  "Majsur": "Mysore", "Makasar": "Makassar", "Makurija": "Makuria", "Malaja": "Malaya",
  "Malavi": "Malawi", "Malezija": "Malaysia", "Mamelučki sultanat": "Mamluk Sultanate", "Mamucij": "Mamucium",
  "Managva": "Managua", "Mandžukuo": "Manchukuo", "Manhajm": "Mannheim", "Mančester": "Manchester",
  "Mapungubve": "Mapungubwe", "Mapuče": "Mapuche", "Marakaibo": "Maracaibo", "Maratska konfederacija": "Maratha Confederacy",
  "Marijenburg": "Marienburg", "Marinidski sultanat": "Marinid Sultanate", "Markomansko kraljevstvo": "Marcomannic Kingdom", "Marksvil": "Marksville",
  "Maroko": "Morocco", "Marselj": "Marseille", "Masačuset": "Massachusett", "Masilija": "Massilia",
  "Maskat": "Muscat", "Mauritanija": "Mauritania", "Mađarska": "Hungary", "Mbudži-Maji": "Mbuji-Mayi",
  "Medeljin": "Medellín", "Meklenburg": "Mecklenburg", "Meksiko": "Mexico", "Meksički zaljev": "Gulf of Mexico",
  "Melburn": "Melbourne", "Merinsko kraljevstvo": "Merina Kingdom", "Meroitsko kraljevstvo": "Kingdom of Meroë", "Mešhed": "Mashhad",
  "Mikstečko carstvo": "Mixtec Empire", "Milano": "Milan", "Milansko vojvodstvo": "Duchy of Milan", "Mineapolis": "Minneapolis",
  "Mingska Kina": "Ming China", "Minhen": "Munich", "Misisipijska kultura": "Mississippian culture", "Mjanmar": "Myanmar",
  "Mletačka republika": "Republic of Venice", "Mogadiš": "Mogadishu", "Mogolistan": "Moghulistan", "Moldavija": "Moldova",
  "Mongolija": "Mongolia", "Monrovija": "Monrovia", "Monterej": "Monterrey", "Mosi kraljevstva": "Mossi kingdoms",
  "Mosijske države": "Mossi states", "Moskovska kneževina": "Grand Duchy of Moscow", "Moskva": "Moscow", "Moundvil": "Moundville",
  "Mozambik": "Mozambique", "Mozambički kanal": "Mozambique Channel", "Moče": "Moche", "Mramorno more": "Sea of Marmara",
  "Mumbaj": "Mumbai", "Nabatejsko kraljevstvo": "Nabataean Kingdom", "Nagoja": "Nagoya", "Najf River": "Knife River",
  "Namibija": "Namibia", "Naning": "Nanning", "Nanjang": "Nanyang", "Nant": "Nantes",
  "Nančang": "Nanchang", "Nančong": "Nanchong", "Napoka": "Napoca", "Napulj": "Naples",
  "Napuljsko kraljevstvo": "Kingdom of Naples", "Nasau": "Nassau", "Naska": "Nazca", "Navara": "Navarre",
  "Ndžamena": "N'Djamena", "Nejpjido": "Naypyidaw", "Niamej": "Niamey", "Nica": "Nice",
  "Nigerija": "Nigeria", "Nikaragva": "Nicaragua", "Nikeja": "Nicaea", "Nikozija": "Nicosia",
  "Nirnberg": "Nuremberg", "Nizozemska": "Netherlands", "Nizva": "Nizwa", "Nižnji Novgorod": "Nizhny Novgorod",
  "Njala": "Nyala", "Njemačka": "Germany", "Njemačko carstvo": "German Empire", "Nju Delhi": "New Delhi",
  "Njufaundlend": "Newfoundland", "Njujork": "New York", "Norveška": "Norway", "Norveško more": "Norwegian Sea",
  "Nova Granada": "New Granada", "Nova Španija": "New Spain", "Novgorodska republika": "Novgorod Republic", "Novi Zeland": "New Zealand",
  "Novonikolajevsk": "Novonikolayevsk", "Nuakšot": "Nouakchott", "Obala Slonovače": "Ivory Coast", "Odesos": "Odessos",
  "Ohotsko more": "Sea of Okhotsk", "Okland": "Auckland", "Olbija": "Olbia", "Osmansko carstvo": "Ottoman Empire",
  "Otava": "Ottawa", "Palestina": "Palestine", "Panorm": "Panormus", "Pantikapej": "Panticapaeum",
  "Papinska država": "Papal States", "Papua Nova Gvineja": "Papua New Guinea", "Papuanska plemena": "Papuan tribes", "Paragvaj": "Paraguay",
  "Pariz": "Paris", "Partsko carstvo": "Parthian Empire", "Patagonci": "Patagonians", "Patra": "Patras",
  "Patre": "Patras", "Peking": "Beijing", "Pekče": "Baekje", "Pert": "Perth",
  "Perzija": "Persia", "Perzijski zaljev": "Persian Gulf", "Pečuh": "Pécs", "Pitsburg": "Pittsburgh",
  "Pišpek": "Pishpek", "Pjinmana": "Pyinmana", "Pjongjang": "Pyongyang", "Pleme Alana": "Alans",
  "Pleme Angla": "Angles", "Pleme Blemija": "Blemmyes", "Pleme Budina": "Budini", "Pleme Esta": "Aesti",
  "Pleme Fena": "Fenni", "Pleme Frizijaca": "Frisii", "Pleme Gauta": "Gauts", "Pleme Gota": "Goths",
  "Pleme Heruska": "Cherusci", "Pleme Jaziga": "Iazyges", "Pleme Roksolana": "Roxolani", "Pleme Sveva": "Suebi",
  "Pleme Sviona": "Suiones", "Pleme Vandala": "Vandals", "Pleme Veneda": "Veneti", "Plemena Arnhema": "Arnhem tribes",
  "Plemena Bagirmija": "Baguirmi tribes", "Plemena Bahr el Gazala": "Bahr el Ghazal tribes", "Plemena Cerada": "Cerrado tribes", "Plemena Darfura": "Darfur tribes",
  "Plemena Kasaija": "Kasai tribes", "Plemena Kimberlija": "Kimberley tribes", "Plemena Konga": "Congo tribes", "Plemena Kvinslenda": "Queensland tribes",
  "Plemena Madagaskara": "Madagascar tribes", "Plemena Malavija": "Malawi tribes", "Plemena Senegambije": "Senegambian tribes", "Plemena Velikih jezera": "Great Lakes tribes",
  "Plemena Velikog bazena": "Great Basin tribes", "Plemena Zambezija": "Zambezi tribes", "Plemena donje Amazone": "Lower Amazon tribes", "Plemena ekvatorijalne šume": "Equatorial forest tribes",
  "Plemena gornje Amazone": "Upper Amazon tribes", "Plemena jugoistoka": "Southeastern tribes", "Plemena južnih ravnica": "Southern Plains tribes", "Plemena pacifičke obale": "Pacific Coast tribes",
  "Plemena pampe": "Pampas tribes", "Plemena pustinje": "Desert tribes", "Plemena rijeke Marej": "Murray River tribes", "Plemena sjevernih ravnica": "Northern Plains tribes",
  "Plemena visoravni": "Plateau tribes", "Plemena zapada": "Western tribes", "Plemena Čaka": "Chaco tribes", "Pnom Pen": "Phnom Penh",
  "Poetovij": "Poetovio", "Poljska": "Poland", "Poljsko-litvanska unija": "Polish–Lithuanian Commonwealth", "Pons Elije": "Pons Aelius",
  "Port Elizabet": "Port Elizabeth", "Port Luj": "Port Louis", "Port Morsbi": "Port Moresby", "Port o Prens": "Port-au-Prince",
  "Port of Spejn": "Port of Spain", "Porto Novo": "Porto-Novo", "Porto Veljo": "Porto Velho", "Portugalski Brazil": "Portuguese Brazil",
  "Portus Kale": "Portus Cale", "Potkraljevstvo Peru": "Viceroyalty of Peru", "Požun": "Pressburg", "Prag": "Prague",
  "Pratišthana": "Pratishthana", "Pretorija": "Pretoria", "Priština": "Pristina", "Pruska": "Prussia",
  "Pruza": "Prusa", "Punaka": "Punakha", "Purušapura": "Purushapura", "Ramala": "Ramallah",
  "Rangun": "Rangoon", "Ravalpindi": "Rawalpindi", "Rejkjavik": "Reykjavík", "Rejni River": "Rainy River",
  "Republika Kina": "Republic of China", "Republika Đenova": "Republic of Genoa", "Resife": "Recife", "Rijad": "Riyadh",
  "Rim": "Rome", "Rimsko carstvo": "Roman Empire", "Rio de Žaneiro": "Rio de Janeiro", "Rostov na Donu": "Rostov-on-Don",
  "Roterdam": "Rotterdam", "Ruanda": "Rwanda", "Rumunija": "Romania", "Rusija": "Russia",
  "Rusko carstvo": "Russian Empire", "SSSR": "USSR", "Sajgon": "Saigon", "Saksonija": "Saxony",
  "San Francisko": "San Francisco", "San Hose": "San José", "San Hoze": "San Jose", "San Huan": "San Juan",
  "Sana": "Sanaa", "Sankt Peterburg": "Saint Petersburg", "Santa Kruz": "Santa Cruz", "Sao Paulo": "São Paulo",
  "Saporo": "Sapporo", "Saragosa": "Zaragoza", "Sarbriken": "Saarbrücken", "Sardinija": "Sardinia",
  "Sarmatija": "Sarmatia", "Satavahansko carstvo": "Satavahana Empire", "Saudijska Arabija": "Saudi Arabia", "Segedin": "Szeged",
  "Selajlo": "Selaylo", "Sendaj": "Sendai", "Sent Džons": "St. John's", "Sent Luis": "St. Louis",
  "Seul": "Seoul", "Sevilja": "Seville", "Sidnej": "Sydney", "Sijam": "Siam",
  "Sijan": "Xi'an", "Sijera Leone": "Sierra Leone", "Sijetl": "Seattle", "Sijudad Huarez": "Ciudad Juárez",
  "Sijudad Truhiljo": "Ciudad Trujillo", "Sikhsko carstvo": "Sikh Empire", "Sikim": "Sikkim", "Sinhalsko kraljevstvo": "Sinhalese Kingdom",
  "Sinsinati": "Cincinnati", "Sirija": "Syria", "Sjamen": "Xiamen", "Sjedinjene Američke Države": "United States",
  "Sjeverna Koreja": "North Korea", "Sjeverna Makedonija": "North Macedonia", "Sjeverni Vijetnam": "North Vietnam", "Sjeverno more": "North Sea",
  "Sjudžou": "Xuzhou", "Skadar": "Shkodër", "Skitija": "Scythia", "Skitski Neapolj": "Scythian Neapolis",
  "Skoplje": "Skopje", "Slobodni grad Krakov": "Free City of Kraków", "Slovačka": "Slovakia", "Slovenija": "Slovenia",
  "Smirna": "Smyrna", "Sofija": "Sofia", "Sokotski kalifat": "Sokoto Caliphate", "Solomonova Ostrva": "Solomon Islands",
  "Solsberi": "Salisbury", "Solt Lejk Siti": "Salt Lake City", "Solun": "Thessaloniki", "Somalija": "Somalia",
  "Sopijane": "Sopianae", "Srbija": "Serbia", "Srednjoazijski hanati": "Central Asian khanates", "Sredozemno more": "Mediterranean Sea",
  "Srpska despotovina": "Serbian Despotate", "Staljino": "Stalino", "Stokholm": "Stockholm", "Sudžou": "Suzhou",
  "Sukhotaj": "Sukhothai", "Sultanat Ifat": "Ifat Sultanate", "Surabaja": "Surabaya", "Surinam": "Suriname",
  "Sučava": "Suceava", "Svahilski gradovi": "Swahili city-states", "Sveto Rimsko Carstvo": "Holy Roman Empire", "Tadžikistan": "Tajikistan",
  "Tajjuan": "Taiyuan", "Tajland": "Thailand", "Tajlandski zaljev": "Gulf of Thailand", "Tajpej": "Taipei",
  "Tajvan": "Taiwan", "Tajčung": "Taichung", "Talin": "Tallinn", "Tanger": "Tangier",
  "Tanzanija": "Tanzania", "Tapažos": "Tapajós", "Tarsatika": "Tarsatica", "Tasmanci": "Tasmanians",
  "Tasmanovo more": "Tasman Sea", "Taškent": "Tashkent", "Tefe": "Tefé", "Tegusigalpa": "Tegucigalpa",
  "Teheran": "Tehran", "Temišvar": "Timișoara", "Tenočtitlan": "Tenochtitlan", "Teotihuakan": "Teotihuacan",
  "Tesalonika": "Thessalonica", "Teutonski red": "Teutonic Order", "Tihi okean": "Pacific Ocean", "Timorsko more": "Timor Sea",
  "Timpu": "Thimphu", "Timuridsko carstvo": "Timurid Empire", "Tiringija": "Thuringia", "Tjenđin": "Tianjin",
  "Tokio": "Tokyo", "Toloza": "Tolosa", "Tongansko carstvo": "Tongan Empire", "Torino": "Turin",
  "Toskana": "Tuscany", "Trapezunt": "Trebizond", "Trapezuntsko carstvo": "Empire of Trebizond", "Travankor": "Travancore",
  "Trgovište": "Târgoviște", "Trinidad i Tobago": "Trinidad and Tobago", "Tripolitanija": "Tripolitania", "Trst": "Trieste",
  "Tuluz": "Toulouse", "Tuniski bejlik": "Beylik of Tunis", "Turikum": "Turicum", "Turska": "Turkey",
  "Ujedinjene provincije Rio de la Plate": "United Provinces of the Río de la Plata", "Ujedinjeni Arapski Emirati": "United Arab Emirates", "Ujedinjeno Kraljevstvo": "United Kingdom", "Ukrajina": "Ukraine",
  "Urugvaj": "Uruguay", "Urumči": "Ürümqi", "Vadžuk": "Wajuk", "Vagadugu": "Ouagadougou",
  "Vajmar": "Weimar", "Valensija": "Valencia", "Valentija": "Valentia", "Vankuver": "Vancouver",
  "Varšava": "Warsaw", "Vašington": "Washington", "Veliki Zimbabve": "Great Zimbabwe", "Veliki australski zaljev": "Great Australian Bight",
  "Velington": "Wellington", "Vendžou": "Wenzhou", "Venecija": "Venice", "Venecuela": "Venezuela",
  "Vidžajanagar": "Vijayanagar", "Vijentijan": "Vientiane", "Vijetnam": "Vietnam", "Vilnjus": "Vilnius",
  "Vindhuk": "Windhoek", "Vinipeg": "Winnipeg", "Virtemberg": "Württemberg", "Višakapatnam": "Visakhapatnam",
  "Vjatka": "Vyatka", "Vlaška": "Wallachia", "Voronjež": "Voronezh", "Vuhan": "Wuhan",
  "Vusi": "Wuxi", "Zaačila": "Zaachila", "Zambija": "Zambia", "Zapadna Njemačka": "West Germany",
  "Zaporožje": "Zaporizhzhia", "Zapoteci": "Zapotecs", "Zapotečko carstvo": "Zapotec Empire", "Zimbabve": "Zimbabwe",
  "Zlatna horda": "Golden Horde", "Ćingdao": "Qingdao", "Ćićihar": "Qiqihar", "Čad": "Chad",
  "Čako": "Chaco", "Čampa": "Champa", "Čan Čan": "Chan Chan", "Čangčun": "Changchun",
  "Čangša": "Changsha", "Čehoslovačka": "Czechoslovakia", "Čenaj": "Chennai", "Čengdu": "Chengdu",
  "Čerepovec": "Cherepovets", "Češka": "Czechia", "Čikago": "Chicago", "Čile": "Chile",
  "Čilikot": "Chilkoot", "Čita": "Chita", "Čitagong": "Chittagong", "Čongking": "Chongqing",
  "Đenova": "Genoa", "Đilin": "Jilin", "Đinan": "Jinan", "Đinsi": "Jinxi",
  "Šabwa": "Shabwa", "Šangaj": "Shanghai", "Šantou": "Shantou", "Šenjang": "Shenyang",
  "Šenžen": "Shenzhen", "Šinđing": "Xinjing", "Šiđadžuang": "Shijiazhuang", "Škotska": "Scotland",
  "Španija": "Spain", "Šri Lanka": "Sri Lanka", "Štutgart": "Stuttgart", "Šuar": "Shuar",
  "Šuari": "Shuar", "Švedska": "Sweden", "Švedska i Norveška": "Sweden and Norway", "Šverin": "Schwerin",
  "Švicarska": "Switzerland", "Ženeva": "Geneva", "Žuto more": "Yellow Sea",
};
